pizza:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

spring:
  data:
    rest:
      base-path: /api

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: threaddump,heapdump

  endpoint:
    health:
      show-details: always

info:
  git:
    mode: full

  #application-description: ^project.description^
  #application-version: ^project.version^

---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost/pizza-cloud
    username: userpizza
    password: passwordpizza
    
logging:
  level:
    pizza: WARN
    
